apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-molknu-app
  namespace: apps
  labels:
    app: go-molknu-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-molknu-app
  template:
    metadata:
      labels:
        app: go-molknu-app
    spec:
      containers:
      - name: go-molknu-app
        image: registry.digitalocean.com/olsen/go-molknu-app:latest
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 200m
          requests:
            cpu: 100m
