apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-molknu
  namespace: apps
  labels:
    k8s-app: go-molknu
spec:
  replicas: 5
  selector:
    matchLabels:
      name: go-molknu
  template:
    metadata:
      labels:
        name: go-molknu
    spec:
      containers:
      - name: application
        image: registry.digitalocean.com/olsen/go-molknu
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080