apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-molknu
spec:
  replicas: 5
  selector:
    matchLabels:
      name: go-molknu
  template:
    metadata:
      labels:
        name: go-molknu
    spec:
      containers:
      - name: application
        image: registry.digitalocean.com/olsen/go-molknu:$(echo $GITHUB_SHA | head -c7)
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080