apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: apps
  name: go-molknu
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  - host: app.motoren.site
  rules:
  - http:
      paths:
      - path: /go-molknu
        pathType: Prefix
        backend:
          service:
            name: go-molknu
            port:
              number: 80