apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: apps
  name: go-molknu-app
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - host: "app.motoren.site"
    http:
      paths:
      - pathType: Prefix
        path: "/go-molknu-app"
        backend:
          service:
            name: go-molknu-app
            port:
              number: 80