name: Build and push container to docker repo olsen @ DO
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Git Checkout
      uses: actions/checkout@v1

    - name: Login to Digital Ocean Registry
      uses: docker/login-action@v1
      with:
        registry: registry.digitalocean.com
        username: ${{ secrets.DIGITAL_OCEAN_TOKEN }}
        password: ${{ secrets.DIGITAL_OCEAN_TOKEN }}

    - name: Build latest
      run: docker build -t registry.digitalocean.com/olsen/go-molknu:$(echo $GITHUB_SHA | head -c7) .
      
    - name: DigitalOcean Docker Image Publish
      # You may pin to the exact commit or the version.
      # uses: ripplr-io/docr-docker-publish@44fac8d6ff7c3ece58c9ffe50f370514d166f5b7
      uses: ripplr-io/docr-docker-publish@v1
      with:
        # Image path in the format registry-name/image-name
        image_path: registry.digitalocean.com/olsen/go-molknu:6430d76
        # Number of characters from the commit SHA
        #sha_size: # optional, default is 8
        # The path + name of the Dockerfile you want to build (-f flag)
        #dockerfile: # optional, default is Dockerfile
        # The docker build context (usually '.')
        #docker_build_context: # optional, default is .
